var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                 v              v                               ",
   "                                                                                ",
   "     *      o      o                                              v             ",
   "                                    xx!!xx                                      ",
   "   xxxxxxxxxxxxxxxxxxxx             v       xxx                                 ",
   "   xxxxxxxxxxxxxxxxxxxxxx                          xx!!!!!!xx                   ",
   "                   xxxxxxxxxxxxx                           v     x!!!x          ",
   "                   xxxxxxxxxxxxx                                                ",
   "                                          o o o                                 ",
   "                                          o   o                            xxx  ",
   "  xx           ~                          o o o                              x  ",
   "  x                     o                                                xxxxx  ",
   "  x      #                                                                   x  ",
   "  x          xxxx       o           xxxxx       xxxxx                   xxxxxx  ",
   "  x  @       x  x                                                            x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx                            xxxxxxxxxxxxxxxxxxx  ",
   "                              x                            x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["       !       !    !        !       !                              v   v  v   v                            *     ",
   "       !       !    !        !       !         xxxxxxxxxxxxxxxxxx                o                                ",
   "       !       !    !        !       !         x                x                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "       !       x    !        x       !         x                x                xxx                           x  ",
   "       !      xxx   !      xxxxx     !         x      o  o      x                  x                x          x  ",
   "       x       x    !        x       !         x                x o      xx        x                           x  ",
   "     xxxxx          !                x         x     xxxxxx     x                  x          xxxxxxxxxxxxxxxxxx  ",
   "       x           x!x              xxx        x     x    x#    xxx                x          x!!!!!!!!!!!!!!!!!! ",
   "                    x                x         x     x    x#    x                  x         xxxxxxxxxxxxxxxxxx!! ",
   "                   x x                         xx    x    x     x        xx      o x         xxxxxxxxxxxxxxxxxx!! ",
   "                                               x  =  x    x     x                  x         x                 !! ",
   "                                               x     x    x    #x                xxx         x                 !! ",
   "             xxxxxxxxxxxxxxxxxxxxxxxx          x    xx    x    #x                  x         x                 !! ",
   "                                    x          x     x    x     x o      xx        x         x                 !! ",
   "                                    x          x     x    x     x                  x         x                 !! ",
   "                                    x          xx    x    x#    xxx                x         x                 !! ",
   "             xxxxxxxxxxxxxxxxxxxx   x          x  =  x    x#    x                  x         x                 !! ",
   "                                x   x          x     x    x     x        xx      o x         x                 !! ",
   "        xxxx                    x o x          x    xx    x     x                  x         x                 !! ",
   "     @         |  ~ |           x   x          x     x    x                      xxx         x                 !! ",
   "    xxx        |    |           x   x          x     x    x                        x         x                 !! ",
   "             xxxxxxxxxxx        x o x          xx    x    x                        x         x                 !! ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   x!!!!!!!!!!x     x!!!!x!!!!xxxxxxxxxxxxxxxxxxxxx!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x   xxxxxxxxxxxx     x!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x o                  x!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                   xx!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    x!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["    v    v    v    v    v    v    v    v #  v    v    v    v    v    v    v    v    v    v    v    v    v    v",
   "                                                                             #                       #       ",
   " #         #      #              #                                                      #                     ",
   "                             #                           xxxxx      #                                         ",
   "     #                                                !                                          #       #    ",
   "                #                             xxxxx            !                                              ",
   "                                  o                                 xxxxx                                     ",
   " =                                                !!!!!!!!!!!!!!!!                                          = ",
   "                                             xxxx!!xxxxx!!!!xxxxx!!               o                           ",
   "                                     xxxxx      !!xxxxxxx!!!!xxxxx!!                                          ",
   "            o               xxxxx               !xxxxxxx!!!!xxxxxxx!            xxxxx       o                 ",
   "                  xxxxx                        !!xxxxxxx!!!!xxxxxxx!! =                                       ",
   "                                               !xxxxxxxx!!!!xxxxxxxx!!                                        ",
   " =        xxxxx                               !!!xxxxxxx!!!!xxxxxxxxx!                   xxxxx              = ",
   "                                             !!xx!!xxxxx!!!!xxxxxxxxx!!                                       ",
   "  xxx                                        !xxxxx!!xxx!!!!xxxxxxxxxx!                                       ",
   "                                            !!xxxxxx!!x!!!!!xxxxxxxx!!!                                       ",
   "  xxxxx                       o            !!xxxxxxxx!!!!!!!xxxxxx!!xxx!                      xxxxx           ",
   "                                          !!xxxxxxxxxx!!!!!!xxxx!!xxxxx!                                      ",
   "        xxxxx                             !xxxxxxxxxxxx!!!!!xxx!!xxxxxx!                                      ",
   "                            xxxxx         !xxxxxxxxxxxx!!!!!x!!xxxxxxxx!!            xxxxx                    ",
   "                 xxxxx                   !!!!!xxxxxxxxx!!!!!!!xxxxxxxxxx!       o                             ",
   "                                     xxxxxxxx!!!!xxxxxx!!!!!!xxxxxxxxxxx!                                     ",
   "                                    xxxxxxxxxxxx!!xxxxx!!!!!xxxxxxxxxx!!!!                                    ",
   "                                      xxxxxxxxxxxx!!xxx!!!!!xxxxxxxxx!!xx!!   xxxxx                           ",
   "                             o   xxxxxxxxxxxxxxxxxxx!!x!!!!!xxxxxxx!!xxxxx!!!                                 ",
   "                                     xxxxxxxxxxxxxxxx!!!!!!!xxxxxx!!xxxxxxxx!               o                 ",
   "                      xxxxx           xxxxxxxxxxxxxxxxx!!!!!xxxxx!!xxxxxxxxxx                                 ",
   "            xxxxx             !!!!!!!!!!!xxxxxxxxxxxxxx!!!!!xxx!!xxxxxxxxxxxx             xxxxx               ",
   "                              !xxxxxxxxx!!!xxxxxxxxxxxx!!!!!xx!!xxxxxxxxxxxxxx                                ",
   "xxx                           !xxxxxxxxxxx!!xxxxxxxxxxx!!!!!!!xxxxxxxxxxxxxxxx                                ",
   "                              !  xxxxxxxxxxx!!!xxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxx                     o         ",
   "                              !  xxxxxxxxxxxxx!!xxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxx                              ",
   "   xxxxx                      !  xxxxxxxxxxxxxxx!!xxxx!!!!!!!xxxxxxxxxxxxxxxxxxx                  xxxxx       ",
   "                              !  xxxxxxxxxxxxxxxx!!!xx!!!!!!!xxxxxxxxxxxxxxxxxxx                              ",
   "              xxxx           !!  xxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxx!!!!                           ",
   "                            !!! xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxx!!xx!!                          ",
   "                        xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!xxxxxxxxxxxx!!xxxx!!!    xxxxx               ",
   "                          xxxxxxxx       xxxxxxxx!!!!!!!!!!!!!!!!!xxxxxxxxx!!xxxxxxxx!!                       ",
   "                          xxxxxxx    ~    xxxxxxx!!!!!!!!!!!!!!!!!!!xxxxx!!xxxxxxxxxxx!!                      ",
   "                                          xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxx!!!                    ",
   "                   xxx                  xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx!!!             *    ",
   "                   xxxxxx      xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxx                ",
   "  @           xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxx            ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                xxxxxxx x    x  xxxx  x    x x   x          x     x  xxxx  x    x                             ",
   "                   x    x    x x    x xx   x x   x           x   x  x    x x    x                             ",
   "                   x    xxxxxx xxxxxx x x  x xxxx              x    x    x x    x                             ",
   "                   x    x    x x    x x  x x x   x             x    x    x x    x                             ",
   "                   x    x    x x    x x   xx x   x             x    x    x x    x                             ",
   "                   x    x    x x    x x    x x   x             x     xxxx   xxxx                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                  xx                                                          ",
   "                                                 x x                                                          ",
   "                                                x  x                                                          ",
   "                                               x   x                                                          ",
   "                                              xxxxxxxx                                                        ",
   "                                                   x                                                          ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                            xxxxx  x       xxxx  x     x  x  x    x  xxxxx                                    ",
   "                            x    x x      x    x  x   x   x  xx   x x     x                                   ",
   "                            xxxxx  x      xxxxxx    x     x  x x  x x                                         ",
   "                            x      x      x    x    x     x  x  x x x  xxxx                                   ",
   "                            x      x      x    x    x     x  x   xx x     x                                   ",
   "                            x      xxxxxx x    x    x     x  x    x  xxxxx                                    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  @                                                                                                           ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
